# Schema for the configuration files of the ONLYOFFICE Connector module.
onlyoffice_connector.settings:
  type: config_object
  label: 'ONLYOFFICE Connector settings'
  mapping:
    doc_server_url:
      type: string
      label: 'Document Editing Service address'
    doc_server_jwt:
      type: string
      label: 'Secret key (leave blank to disable)'
